version: "3.3"
services:
  tortoise_test:
    build: .
    container_name: "tortoise_test"
    restart: always
    env_file:
      - .env
    depends_on:
      - bot_db
    ports:
      - "10000:5000"
    command: ["python3", "main_script.py"]

#  tortoise_test_db:
#    image: postgres:15.1
#    container_name: "tortoise_test_db"
#    restart: always
#    env_file:
#      - postgres.env
#    ports:
#      - "10001:5432"
